// src/app/layout.tsx

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';
import { CartProvider } from '../context/CartContext'; 
import { SearchProvider } from '../context/SearchContext';
import 'bootstrap/dist/css/bootstrap.min.css';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Handcrafted Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <SearchProvider>
      <CartProvider> {/* Wrap children with CartProvider */}
          <Header /> {/* Header displayed before the main content */}
          <main>
            {children} {/* Main content of the page */}
          </main>
          <Footer /> {/* Footer displayed after the main content */}
        </CartProvider>
      </SearchProvider>

       
      </body>
    </html>
  );
}
